### ISSUE TITLE
Global Text Search

### ISSUE THREAD

**Issue by DutMsn** [IvorySQL/ivory-doc-builder#6]
[IvorySQL Doc center](https://docs.ivorysql.org/) requires a global text search function. So, when people read this website, they can quickly find the content they want to know.

**Comment by DutMsn** [comment]
![image](https://github.com/IvorySQL/ivory-doc-builder/assets/41883314/546ae2d9-a0fb-4899-90dc-d375780d91be)

We want the search box to appear in the position shown in the diagram.

**Comment by balinorLiang** [comment]
This enhancement has been finished in #9
